<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.basicframework</groupId>
        <artifactId>basic-framework-core</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>basic-framework-spring-boot-starter-mq</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>消息队列，支持 Redis 与 RabbitMQ</description>
    <url>https://example.com/basic-framework</url>

    <dependencies>
        <!-- DB 相关 -->
        <dependency>
            <groupId>com.basicframework</groupId>
            <artifactId>basic-framework-spring-boot-starter-redis</artifactId>
        </dependency>

        <!-- 消息队列相关 -->
        <dependency>
            <groupId>org.springframework.amqp</groupId>
            <artifactId>spring-rabbit</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- 单元测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
