/**
 * 精选图标清单：从 lucide-vue-next 转发框架界面实际使用的图标组件。
 * 用白名单控制体积，Menu、ArrowLeftFromLine 等按框架语义改名后导出，
 * 原名不再暴露；模板里新增图标必须在此登记。
 */
export {
  ArrowDown,
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUpToLine,
  Bell,
  BookOpenText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CircleX,
  CloudUpload,
  Copy,
  CornerDownLeft,
  Download,
  Ellipsis,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FoldHorizontal,
  Fullscreen,
  Grid,
  Grip,
  GripVertical,
  History,
  Menu as IconDefault,
  Inbox,
  Info,
  InspectionPanel,
  Languages,
  LayoutGrid,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  MailCheck,
  Maximize,
  ArrowRightFromLine as MdiMenuClose,
  ArrowLeftFromLine as MdiMenuOpen,
  Menu,
  Minimize,
  Minimize2,
  MoonStar,
  Palette,
  PanelLeft,
  PanelRight,
  Pin,
  PinOff,
  Plus,
  RefreshCw,
  RotateCw,
  Search,
  SearchX,
  Settings,
  ShieldQuestion,
  Shrink,
  Square,
  SquareCheckBig,
  SquareMinus,
  Sun,
  SunMoon,
  SwatchBook,
  Trash2,
  Upload,
  UserRoundPen,
  X,
} from 'lucide-vue-next';
